### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by daxpedda**
Just found a typo on the front page.

### CODE REVIEW

**Comment by daxpedda** [comment]
Hm, I don't think I feel entirely comfortable sharing my physical address with Eclipse just to sign the contributors agreement.

**Comment by p-avital** [comment]
Hi, 

That's understandable, if you'd still like your commit to be on there, we've had precedents in Zenoh of people with the same position as you, whose PR was merged after they posted the following:

```
I state that I was not able to sign ECA with my GitHub private email,
since I wouldn't want to disclose my public email for this particular commit,
and that therefore I grant the permission to copy/merge my PR if accepted
```

If that suits you better, feel free to just reopen and reply with that, and I'll merge your PR :)

**Comment by daxpedda** [comment]
I state that I was not able to sign ECA with my GitHub private email,
since I wouldn't want to disclose my public email for this particular commit,
and that therefore I grant the permission to copy/merge my PR if accepted

**Review by p-avital — APPROVED** [review]

**Comment by daxpedda** [comment]
I think some contributor guidelines would help with stuff like that.
See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors.

**Comment by p-avital** [comment]
Yup, I just added a `CONTRIBUTING.md` :)

**Pull request merged**
